// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// prior_nonc_t
double prior_nonc_t(const double a1, const double p1, const double sigma1, const double nu, const double lam1);
RcppExport SEXP _BHSBVAR_prior_nonc_t(SEXP a1SEXP, SEXP p1SEXP, SEXP sigma1SEXP, SEXP nuSEXP, SEXP lam1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const double >::type lam1(lam1SEXP);
    rcpp_result_gen = Rcpp::wrap(prior_nonc_t(a1, p1, sigma1, nu, lam1));
    return rcpp_result_gen;
END_RCPP
}
// prior_t_n
double prior_t_n(const double a1, const double p1, const double sigma1, const double nu);
RcppExport SEXP _BHSBVAR_prior_t_n(SEXP a1SEXP, SEXP p1SEXP, SEXP sigma1SEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t_n(a1, p1, sigma1, nu));
    return rcpp_result_gen;
END_RCPP
}
// prior_t_p
double prior_t_p(const double a1, const double p1, const double sigma1, const double nu);
RcppExport SEXP _BHSBVAR_prior_t_p(SEXP a1SEXP, SEXP p1SEXP, SEXP sigma1SEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t_p(a1, p1, sigma1, nu));
    return rcpp_result_gen;
END_RCPP
}
// prior_t
double prior_t(const double a1, const double p1, const double sigma1, const double nu);
RcppExport SEXP _BHSBVAR_prior_t(SEXP a1SEXP, SEXP p1SEXP, SEXP sigma1SEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t(a1, p1, sigma1, nu));
    return rcpp_result_gen;
END_RCPP
}
// prior_beta
double prior_beta(const double a1, const double sh1, const double sh2);
RcppExport SEXP _BHSBVAR_prior_beta(SEXP a1SEXP, SEXP sh1SEXP, SEXP sh2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type sh1(sh1SEXP);
    Rcpp::traits::input_parameter< const double >::type sh2(sh2SEXP);
    rcpp_result_gen = Rcpp::wrap(prior_beta(a1, sh1, sh2));
    return rcpp_result_gen;
END_RCPP
}
// prior_ibeta
double prior_ibeta(const double a1, const double sh1, const double sh2);
RcppExport SEXP _BHSBVAR_prior_ibeta(SEXP a1SEXP, SEXP sh1SEXP, SEXP sh2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type sh1(sh1SEXP);
    Rcpp::traits::input_parameter< const double >::type sh2(sh2SEXP);
    rcpp_result_gen = Rcpp::wrap(prior_ibeta(a1, sh1, sh2));
    return rcpp_result_gen;
END_RCPP
}
// sum_log_prior_densities
double sum_log_prior_densities(const arma::mat& A_test, const arma::cube& pA, const arma::cube& pdetA, const arma::cube& pH);
RcppExport SEXP _BHSBVAR_sum_log_prior_densities(SEXP A_testSEXP, SEXP pASEXP, SEXP pdetASEXP, SEXP pHSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A_test(A_testSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pA(pASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pdetA(pdetASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pH(pHSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_log_prior_densities(A_test, pA, pdetA, pH));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_function
double log_likelihood_function(const arma::mat& A_test, const arma::mat& kappa1, const arma::mat& y1, const arma::mat& omega, const arma::mat& zeta_test, const arma::mat& somega);
RcppExport SEXP _BHSBVAR_log_likelihood_function(SEXP A_testSEXP, SEXP kappa1SEXP, SEXP y1SEXP, SEXP omegaSEXP, SEXP zeta_testSEXP, SEXP somegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A_test(A_testSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kappa1(kappa1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type zeta_test(zeta_testSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type somega(somegaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_function(A_test, kappa1, y1, omega, zeta_test, somega));
    return rcpp_result_gen;
END_RCPP
}
// hd_estimates
arma::cube hd_estimates(const arma::cube& A_chain, const arma::cube& B_chain, const arma::mat& y1, const arma::mat& x1, const arma::uword nlags, const double ci);
RcppExport SEXP _BHSBVAR_hd_estimates(SEXP A_chainSEXP, SEXP B_chainSEXP, SEXP y1SEXP, SEXP x1SEXP, SEXP nlagsSEXP, SEXP ciSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type A_chain(A_chainSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type B_chain(B_chainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nlags(nlagsSEXP);
    Rcpp::traits::input_parameter< const double >::type ci(ciSEXP);
    rcpp_result_gen = Rcpp::wrap(hd_estimates(A_chain, B_chain, y1, x1, nlags, ci));
    return rcpp_result_gen;
END_RCPP
}
// irf_estimates
arma::cube irf_estimates(const arma::cube& A_chain, const arma::cube& B_chain, const arma::uword nlags, const arma::uword h, const bool acc, const double ci);
RcppExport SEXP _BHSBVAR_irf_estimates(SEXP A_chainSEXP, SEXP B_chainSEXP, SEXP nlagsSEXP, SEXP hSEXP, SEXP accSEXP, SEXP ciSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type A_chain(A_chainSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type B_chain(B_chainSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nlags(nlagsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type h(hSEXP);
    Rcpp::traits::input_parameter< const bool >::type acc(accSEXP);
    Rcpp::traits::input_parameter< const double >::type ci(ciSEXP);
    rcpp_result_gen = Rcpp::wrap(irf_estimates(A_chain, B_chain, nlags, h, acc, ci));
    return rcpp_result_gen;
END_RCPP
}
// fevd_estimates
arma::cube fevd_estimates(const arma::cube& A_chain, const arma::cube& B_chain, const arma::cube& D_chain, const arma::uword nlags, const arma::uword h, const bool acc, const double ci);
RcppExport SEXP _BHSBVAR_fevd_estimates(SEXP A_chainSEXP, SEXP B_chainSEXP, SEXP D_chainSEXP, SEXP nlagsSEXP, SEXP hSEXP, SEXP accSEXP, SEXP ciSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type A_chain(A_chainSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type B_chain(B_chainSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type D_chain(D_chainSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nlags(nlagsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type h(hSEXP);
    Rcpp::traits::input_parameter< const bool >::type acc(accSEXP);
    Rcpp::traits::input_parameter< const double >::type ci(ciSEXP);
    rcpp_result_gen = Rcpp::wrap(fevd_estimates(A_chain, B_chain, D_chain, nlags, h, acc, ci));
    return rcpp_result_gen;
END_RCPP
}
// MAIN
Rcpp::List MAIN(const arma::mat& y1, const arma::mat& x1, const arma::mat& omega, const arma::mat& somega, const arma::uword nlags, const arma::cube& pA, const arma::cube& pdetA, const arma::cube& pH, const arma::mat& pP, const arma::mat& pP_sig, const arma::cube& pR_sig, const arma::mat& kappa1, const arma::mat& A_start, const arma::uword itr, const arma::uword burn, const arma::uword thin, const arma::mat& scale1, const double ci);
RcppExport SEXP _BHSBVAR_MAIN(SEXP y1SEXP, SEXP x1SEXP, SEXP omegaSEXP, SEXP somegaSEXP, SEXP nlagsSEXP, SEXP pASEXP, SEXP pdetASEXP, SEXP pHSEXP, SEXP pPSEXP, SEXP pP_sigSEXP, SEXP pR_sigSEXP, SEXP kappa1SEXP, SEXP A_startSEXP, SEXP itrSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP scale1SEXP, SEXP ciSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type somega(somegaSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nlags(nlagsSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pA(pASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pdetA(pdetASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pH(pHSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pP(pPSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pP_sig(pP_sigSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pR_sig(pR_sigSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kappa1(kappa1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A_start(A_startSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type itr(itrSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< const double >::type ci(ciSEXP);
    rcpp_result_gen = Rcpp::wrap(MAIN(y1, x1, omega, somega, nlags, pA, pdetA, pH, pP, pP_sig, pR_sig, kappa1, A_start, itr, burn, thin, scale1, ci));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BHSBVAR_prior_nonc_t", (DL_FUNC) &_BHSBVAR_prior_nonc_t, 5},
    {"_BHSBVAR_prior_t_n", (DL_FUNC) &_BHSBVAR_prior_t_n, 4},
    {"_BHSBVAR_prior_t_p", (DL_FUNC) &_BHSBVAR_prior_t_p, 4},
    {"_BHSBVAR_prior_t", (DL_FUNC) &_BHSBVAR_prior_t, 4},
    {"_BHSBVAR_prior_beta", (DL_FUNC) &_BHSBVAR_prior_beta, 3},
    {"_BHSBVAR_prior_ibeta", (DL_FUNC) &_BHSBVAR_prior_ibeta, 3},
    {"_BHSBVAR_sum_log_prior_densities", (DL_FUNC) &_BHSBVAR_sum_log_prior_densities, 4},
    {"_BHSBVAR_log_likelihood_function", (DL_FUNC) &_BHSBVAR_log_likelihood_function, 6},
    {"_BHSBVAR_hd_estimates", (DL_FUNC) &_BHSBVAR_hd_estimates, 6},
    {"_BHSBVAR_irf_estimates", (DL_FUNC) &_BHSBVAR_irf_estimates, 6},
    {"_BHSBVAR_fevd_estimates", (DL_FUNC) &_BHSBVAR_fevd_estimates, 7},
    {"_BHSBVAR_MAIN", (DL_FUNC) &_BHSBVAR_MAIN, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_BHSBVAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
